[server]
headless = true
port = 8501
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#8B5CF6"
backgroundColor = "#080810"
secondaryBackgroundColor = "#151522"
textColor = "#F7F5FF"
font = "sans serif"
